# Homebrew repositories
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

# Third-party repositories
tap "cjbassi/gotop"
tap "jesseduffield/lazydocker"
tap "neovim/neovim"
tap "xo/xo"

# CLI tools
brew "abook"
brew "autojump"
brew "bandwhich"
brew "bat"
brew "calcurse"
brew "cjbassi/gotop/gotop"
brew "diskonaut"
brew "exa"
brew "fd"
brew "fswatch"
brew "fzf"
brew "httpie"
brew "jesseduffield/lazydocker/lazydocker"
brew "jq"
brew "lazygit"
brew "lf"
brew "n"
brew "neofetch"
brew "neovim"
brew "newsboat"
brew "nmap"
brew "p7zip"
brew "postgresql"
brew "procs"
brew "ripgrep"
brew "starship"
brew "stow"
brew "thefuck"
brew "trash-cli"
brew "watch"
brew "xo/xo/usql"
brew "youtube-dl"

