# Homebrew repositories
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

# Third-party repositories
tap "cjbassi/gotop"
tap "jesseduffield/lazydocker"
tap "neovim/neovim"
tap "xo/xo"

# CLI tools
brew "autojump"
brew "bat"
brew "cjbassi/gotop/gotop"
brew "exa"
brew "fd"
brew "fswatch"
brew "fzf"
brew "httpie"
brew "jesseduffield/lazydocker/lazydocker"
brew "jq"
brew "lf"
brew "neofetch"
brew "neovim"
brew "newsboat"
brew "nmap"
brew "node"
brew "p7zip"
brew "postgresql"
brew "ripgrep"
brew "sc-im"
brew "screenfetch"
brew "sl"
brew "thefuck"
brew "watch"
brew "wget"
brew "xo/xo/usql"
brew "youtube-dl"

# Misc.
cask "alacritty"
cask "chromedriver"
cask "font-jetbrainsmono-nerd-font"
cask "mpv"
