#!/usr/bin/env sh
yabai -m config layout bsp
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.5

yabai -m config window_border on
yabai -m config window_border_width 2
yabai -m config window_border_radius -1.0
yabai -m config active_window_border_color 0xff8FBCBB
yabai -m config normal_window_border_color 0xff3B4252
yabai -m config insert_window_border_color 0xffff0000

yabai -m config top_padding    5
yabai -m config bottom_padding 5
yabai -m config left_padding   5
yabai -m config right_padding  5
yabai -m config window_gap     5

yabai -m rule --add app="^System Preferences$"  manage=off border=off
